// How object types connect. Each link is declared once, from the "one" side.

import type { LinkTypeDefinition } from './types';

export const LINK_TYPES = {
  // ─── Loadout ───────────────────────────────────────────────────────
  'site-staging-lanes': {
    apiName: 'site-staging-lanes',
    displayName: 'Site → Staging Lanes',
    description: 'Every staging lane belongs to one site.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Site',
    targetObjectType: 'StagingLane',
    foreignKeyProperty: 'siteId',
    sourceToTarget: 'stagingLanes',
    targetToSource: 'site',
  },
  'site-loads': {
    apiName: 'site-loads',
    displayName: 'Site → Loads',
    description: 'Loads are shipped from one site.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Site',
    targetObjectType: 'Load',
    foreignKeyProperty: 'siteId',
    sourceToTarget: 'loads',
    targetToSource: 'site',
  },
  'lane-current-load': {
    apiName: 'lane-current-load',
    displayName: 'Staging Lane → Current Load',
    description:
      'A lane holds at most one load at a time; a load occupies at most one lane.',
    cardinality: 'ONE_TO_ONE',
    sourceObjectType: 'Load',
    targetObjectType: 'StagingLane',
    foreignKeyProperty: 'currentLoadId',
    sourceToTarget: 'stagingLane',
    targetToSource: 'currentLoad',
  },
  'load-pallets': {
    apiName: 'load-pallets',
    displayName: 'Load → Pallets',
    description: 'Pallets scanned onto a load.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Load',
    targetObjectType: 'Pallet',
    foreignKeyProperty: 'loadId',
    sourceToTarget: 'pallets',
    targetToSource: 'load',
  },
  'lane-pallets': {
    apiName: 'lane-pallets',
    displayName: 'Staging Lane → Pallets',
    description: 'Pallets physically sitting in a lane.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'StagingLane',
    targetObjectType: 'Pallet',
    foreignKeyProperty: 'stagingLaneId',
    sourceToTarget: 'pallets',
    targetToSource: 'stagingLane',
  },
  'load-inspections': {
    apiName: 'load-inspections',
    displayName: 'Load → Inspections',
    description: 'Inspection results recorded against a load.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Load',
    targetObjectType: 'Inspection',
    foreignKeyProperty: 'loadId',
    sourceToTarget: 'inspections',
    targetToSource: 'load',
  },
  'pallet-inspections': {
    apiName: 'pallet-inspections',
    displayName: 'Pallet → Inspections',
    description: 'Inspection results scoped to a single pallet.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Pallet',
    targetObjectType: 'Inspection',
    foreignKeyProperty: 'palletId',
    sourceToTarget: 'inspections',
    targetToSource: 'pallet',
  },
  'site-loadout-inspections': {
    apiName: 'site-loadout-inspections',
    displayName: 'Site → Loadout Inspections',
    description: 'Field inspections captured at a site.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Site',
    targetObjectType: 'LoadoutInspection',
    foreignKeyProperty: 'siteId',
    sourceToTarget: 'loadoutInspections',
    targetToSource: 'site',
  },
  'site-inspectors': {
    apiName: 'site-inspectors',
    displayName: 'Site → Inspectors',
    description: 'Inspectors selectable at a site.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Site',
    targetObjectType: 'Inspector',
    foreignKeyProperty: 'siteId',
    sourceToTarget: 'inspectors',
    targetToSource: 'site',
  },

  // ─── DockX ─────────────────────────────────────────────────────────
  'appointment-pit-task': {
    apiName: 'appointment-pit-task',
    displayName: 'Appointment → PIT Task',
    description: 'Each appointment has at most one PIT task.',
    cardinality: 'ONE_TO_ONE',
    sourceObjectType: 'Appointment',
    targetObjectType: 'PitTask',
    foreignKeyProperty: 'appointmentId',
    sourceToTarget: 'pitTask',
    targetToSource: 'appointment',
  },
  'door-appointments': {
    apiName: 'door-appointments',
    displayName: 'Door → Appointments',
    description: 'Appointments assigned to a door at check-in.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Door',
    targetObjectType: 'Appointment',
    foreignKeyProperty: 'doorId',
    sourceToTarget: 'appointments',
    targetToSource: 'door',
  },
  'operator-appointments': {
    apiName: 'operator-appointments',
    displayName: 'Operator → Appointments',
    description: 'Appointments an operator is working.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Operator',
    targetObjectType: 'Appointment',
    foreignKeyProperty: 'operatorId',
    sourceToTarget: 'appointments',
    targetToSource: 'operator',
  },

  // ─── Operations Hub ────────────────────────────────────────────────
  'employee-skill-ratings': {
    apiName: 'employee-skill-ratings',
    displayName: 'Employee → Skill Ratings',
    description: 'Assessments recorded for an employee.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Employee',
    targetObjectType: 'EmployeeSkill',
    foreignKeyProperty: 'employeeId',
    sourceToTarget: 'skillRatings',
    targetToSource: 'employee',
  },
  'employee-coaching': {
    apiName: 'employee-coaching',
    displayName: 'Employee → Coaching',
    description: 'Coaching opportunities opened for an employee.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Employee',
    targetObjectType: 'Coaching',
    foreignKeyProperty: 'employeeId',
    sourceToTarget: 'coaching',
    targetToSource: 'employee',
  },
  'employee-equipment': {
    apiName: 'employee-equipment',
    displayName: 'Employee → Equipment',
    description: 'Equipment currently assigned to an employee.',
    cardinality: 'ONE_TO_MANY',
    sourceObjectType: 'Employee',
    targetObjectType: 'Equipment',
    foreignKeyProperty: 'assignedToId',
    sourceToTarget: 'equipment',
    targetToSource: 'assignedTo',
  },
} as const satisfies Record<string, LinkTypeDefinition>;

export type LinkTypeApiName = keyof typeof LINK_TYPES;
