// Every object type in the GXO ontology — the complete list of things we store.
//
// `apiPath` is the segment served by `GET /api/ontology/{apiPath}`; object types
// with a null `apiPath` are not exposed as a read endpoint (today, only the
// offline-first Loadout records, which live in IndexedDB on the device).

import type { ObjectTypeDefinition } from './types';

export const OBJECT_TYPES = {
  // ─── Loadout domain ────────────────────────────────────────────────
  Site: {
    apiName: 'Site',
    displayName: 'Site',
    pluralDisplayName: 'Sites',
    description: 'A physical facility. Root of the loadout hierarchy.',
    domain: 'loadout',
    storage: 'RELATIONAL',
    apiPath: 'sites',
    backingModel: 'Site',
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'name',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      timezone: {
        apiName: 'timezone',
        displayName: 'Timezone',
        baseType: 'string',
        description: 'IANA timezone used to interpret local dock times.',
      },
      address: {
        apiName: 'address',
        displayName: 'Address',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  StagingLane: {
    apiName: 'StagingLane',
    displayName: 'Staging Lane',
    pluralDisplayName: 'Staging Lanes',
    description:
      'A floor position where an outbound load is staged before loading.',
    domain: 'loadout',
    storage: 'RELATIONAL',
    apiPath: 'staging-lanes',
    backingModel: 'StagingLane',
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'name',
    statusProperty: 'status',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      zoneCode: {
        apiName: 'zoneCode',
        displayName: 'Zone Code',
        baseType: 'string',
        description: 'Warehouse zone the lane sits in.',
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'LaneStatus',
      },
      coordinates: {
        apiName: 'coordinates',
        displayName: 'Coordinates',
        baseType: 'struct',
        description: 'Map footprint: { x, y, width, length }.',
      },
      currentLoadId: {
        apiName: 'currentLoadId',
        displayName: 'Current Load',
        baseType: 'string',
        nullable: true,
      },
      siteId: {
        apiName: 'siteId',
        displayName: 'Site',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Load: {
    apiName: 'Load',
    displayName: 'Load',
    pluralDisplayName: 'Loads',
    description:
      'An outbound shipment. Load number and BOL number are the same value.',
    domain: 'loadout',
    storage: 'RELATIONAL',
    apiPath: 'loads',
    backingModel: 'Load',
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'carrier',
    statusProperty: 'status',
    properties: {
      carrier: { apiName: 'carrier', displayName: 'Carrier', baseType: 'string' },
      destination: {
        apiName: 'destination',
        displayName: 'Destination',
        baseType: 'string',
        nullable: true,
      },
      expectedPalletCount: {
        apiName: 'expectedPalletCount',
        displayName: 'Expected Pallets',
        baseType: 'integer',
        description: 'Pallet count from the picklist, used to reconcile scans.',
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'LoadStatus',
      },
      siteId: {
        apiName: 'siteId',
        displayName: 'Site',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Pallet: {
    apiName: 'Pallet',
    displayName: 'Pallet',
    pluralDisplayName: 'Pallets',
    description: 'A scanned physical pallet belonging to a load.',
    domain: 'loadout',
    storage: 'RELATIONAL',
    apiPath: 'pallets',
    backingModel: 'Pallet',
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'barcode',
    properties: {
      barcode: {
        apiName: 'barcode',
        displayName: 'Barcode',
        baseType: 'string',
        description: 'Unique LPN/barcode scanned on the floor.',
      },
      productType: {
        apiName: 'productType',
        displayName: 'Product Type',
        baseType: 'string',
        nullable: true,
      },
      packagingType: {
        apiName: 'packagingType',
        displayName: 'Packaging Type',
        baseType: 'string',
        nullable: true,
        valueType: 'PackagingType',
      },
      isFlagged: {
        apiName: 'isFlagged',
        displayName: 'Flagged',
        baseType: 'boolean',
        description: 'Set when an inspector raised a quality flag.',
      },
      loadId: {
        apiName: 'loadId',
        displayName: 'Load',
        baseType: 'string',
        nullable: true,
      },
      stagingLaneId: {
        apiName: 'stagingLaneId',
        displayName: 'Staging Lane',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Inspection: {
    apiName: 'Inspection',
    displayName: 'Inspection',
    pluralDisplayName: 'Inspections',
    description:
      'A submitted inspection result against a load, optionally scoped to one pallet.',
    domain: 'loadout',
    storage: 'RELATIONAL',
    apiPath: 'inspections',
    backingModel: 'Inspection',
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'inspectorName',
    statusProperty: 'result',
    properties: {
      inspectorName: {
        apiName: 'inspectorName',
        displayName: 'Inspector',
        baseType: 'string',
      },
      timestamp: {
        apiName: 'timestamp',
        displayName: 'Recorded At',
        baseType: 'timestamp',
      },
      photos: {
        apiName: 'photos',
        displayName: 'Photos',
        baseType: 'string[]',
        description: 'Photo URLs; persisted as a JSON string column.',
      },
      notes: {
        apiName: 'notes',
        displayName: 'Notes',
        baseType: 'string',
        nullable: true,
      },
      result: {
        apiName: 'result',
        displayName: 'Result',
        baseType: 'string',
        valueType: 'InspectionResult',
      },
      loadId: { apiName: 'loadId', displayName: 'Load', baseType: 'string' },
      palletId: {
        apiName: 'palletId',
        displayName: 'Pallet',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  // ─── Loadout domain: offline-first records ─────────────────────────
  LoadoutInspection: {
    apiName: 'LoadoutInspection',
    displayName: 'Loadout Inspection',
    pluralDisplayName: 'Loadout Inspections',
    description:
      'The full field-inspection document captured on the tablet: picklist, BOL, per-pallet results and staging checks. Held in IndexedDB and synced up on completion.',
    domain: 'loadout',
    storage: 'LOCAL_FIRST',
    apiPath: null,
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'id',
    statusProperty: 'status',
    properties: {
      type: {
        apiName: 'type',
        displayName: 'Type',
        baseType: 'string',
        valueType: 'InspectionType',
      },
      siteId: { apiName: 'siteId', displayName: 'Site', baseType: 'string' },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'InspectionStatus',
      },
      pickerName: {
        apiName: 'pickerName',
        displayName: 'Picker',
        baseType: 'string',
        nullable: true,
      },
      startedBy: {
        apiName: 'startedBy',
        displayName: 'Started By',
        baseType: 'string',
        nullable: true,
      },
      startedAt: {
        apiName: 'startedAt',
        displayName: 'Started At',
        baseType: 'timestamp',
      },
      completedBy: {
        apiName: 'completedBy',
        displayName: 'Completed By',
        baseType: 'string',
        nullable: true,
      },
      completedAt: {
        apiName: 'completedAt',
        displayName: 'Completed At',
        baseType: 'timestamp',
        nullable: true,
      },
      lastEditedBy: {
        apiName: 'lastEditedBy',
        displayName: 'Last Edited By',
        baseType: 'string',
        nullable: true,
      },
      lastEditedAt: {
        apiName: 'lastEditedAt',
        displayName: 'Last Edited At',
        baseType: 'timestamp',
        nullable: true,
      },
      currentInspector: {
        apiName: 'currentInspector',
        displayName: 'Current Inspector',
        baseType: 'string',
        nullable: true,
        description: 'Changes on handoff; each pallet also records its scanner.',
      },
      handoffLog: {
        apiName: 'handoffLog',
        displayName: 'Handoff Log',
        baseType: 'struct[]',
        nullable: true,
      },
      stagingLocation: {
        apiName: 'stagingLocation',
        displayName: 'Staging Location',
        baseType: 'string',
        nullable: true,
      },
      picklist: {
        apiName: 'picklist',
        displayName: 'Picklist',
        baseType: 'struct',
        description: 'Captured picklist header plus line items.',
      },
      bol: {
        apiName: 'bol',
        displayName: 'BOL',
        baseType: 'struct',
        description: 'Captured BOL header plus deliveries/stops.',
      },
      returnsBol: {
        apiName: 'returnsBol',
        displayName: 'Returns BOL',
        baseType: 'struct',
        nullable: true,
      },
      returnsBrand: {
        apiName: 'returnsBrand',
        displayName: 'Returns Brand',
        baseType: 'string',
        nullable: true,
        valueType: 'ReturnsBrand',
      },
      crossReference: {
        apiName: 'crossReference',
        displayName: 'Cross Reference',
        baseType: 'struct',
        nullable: true,
        description: 'Computed picklist-vs-BOL discrepancies.',
      },
      pallets: {
        apiName: 'pallets',
        displayName: 'Pallets',
        baseType: 'struct[]',
        description: 'Per-pallet inspection results, batch sections and photos.',
      },
      staging: {
        apiName: 'staging',
        displayName: 'Staging',
        baseType: 'struct',
        description: 'End-of-load staging checklist and overview photos.',
      },
      qualityFlag: {
        apiName: 'qualityFlag',
        displayName: 'Quality Flag',
        baseType: 'struct',
        nullable: true,
      },
      flaggedItemsCount: {
        apiName: 'flaggedItemsCount',
        displayName: 'Flagged Items',
        baseType: 'integer',
      },
      archived: {
        apiName: 'archived',
        displayName: 'Archived',
        baseType: 'boolean',
        nullable: true,
      },
    },
  },

  Inspector: {
    apiName: 'Inspector',
    displayName: 'Inspector',
    pluralDisplayName: 'Inspectors',
    description:
      'A person who can be selected as inspector on a device. Admin-editable, stored per device.',
    domain: 'loadout',
    storage: 'LOCAL_FIRST',
    apiPath: null,
    primaryKey: 'id',
    primaryKeyType: 'string',
    titleProperty: 'name',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      siteId: { apiName: 'siteId', displayName: 'Site', baseType: 'string' },
      active: { apiName: 'active', displayName: 'Active', baseType: 'boolean' },
    },
  },

  // ─── DockX domain ──────────────────────────────────────────────────
  Appointment: {
    apiName: 'Appointment',
    displayName: 'Appointment',
    pluralDisplayName: 'Appointments',
    description: 'A scheduled inbound or outbound dock appointment.',
    domain: 'dockx',
    storage: 'RELATIONAL',
    apiPath: 'appointments',
    backingModel: 'Appointment',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'bolShipmentNo',
    statusProperty: 'status',
    properties: {
      date: {
        apiName: 'date',
        displayName: 'Date',
        baseType: 'date',
        description: 'Scheduled date, YYYY-MM-DD.',
      },
      time: {
        apiName: 'time',
        displayName: 'Time',
        baseType: 'string',
        description: 'Scheduled local time, HH:MM.',
      },
      type: {
        apiName: 'type',
        displayName: 'Type',
        baseType: 'string',
        valueType: 'AppointmentType',
      },
      carrier: { apiName: 'carrier', displayName: 'Carrier', baseType: 'string' },
      bolShipmentNo: {
        apiName: 'bolShipmentNo',
        displayName: 'BOL / Shipment #',
        baseType: 'string',
      },
      customer: {
        apiName: 'customer',
        displayName: 'Customer',
        baseType: 'string',
      },
      productType: {
        apiName: 'productType',
        displayName: 'Product Type',
        baseType: 'string',
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'AppointmentStatus',
      },
      doorId: {
        apiName: 'doorId',
        displayName: 'Door',
        baseType: 'integer',
        nullable: true,
      },
      doorName: {
        apiName: 'doorName',
        displayName: 'Door Name',
        baseType: 'string',
        nullable: true,
        description: 'Denormalized from the assigned Door at check-in.',
      },
      operatorId: {
        apiName: 'operatorId',
        displayName: 'Operator',
        baseType: 'integer',
        nullable: true,
      },
      operatorName: {
        apiName: 'operatorName',
        displayName: 'Operator Name',
        baseType: 'string',
        nullable: true,
        description: 'Denormalized from the assigned Operator at check-in.',
      },
      checkInTime: {
        apiName: 'checkInTime',
        displayName: 'Check-In Time',
        baseType: 'timestamp',
        nullable: true,
      },
      checkOutTime: {
        apiName: 'checkOutTime',
        displayName: 'Check-Out Time',
        baseType: 'timestamp',
        nullable: true,
      },
      dwellTime: {
        apiName: 'dwellTime',
        displayName: 'Dwell Time',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Door: {
    apiName: 'Door',
    displayName: 'Door',
    pluralDisplayName: 'Doors',
    description: 'A dock door appointments are assigned to.',
    domain: 'dockx',
    storage: 'RELATIONAL',
    apiPath: 'doors',
    backingModel: 'Door',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'name',
    statusProperty: 'status',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      direction: {
        apiName: 'direction',
        displayName: 'Direction',
        baseType: 'string',
        valueType: 'DoorDirection',
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'DoorStatus',
      },
    },
  },

  Operator: {
    apiName: 'Operator',
    displayName: 'Operator',
    pluralDisplayName: 'Operators',
    description: 'A PIT operator available for dock work.',
    domain: 'dockx',
    storage: 'RELATIONAL',
    apiPath: 'operators',
    backingModel: 'Operator',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'name',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
    },
  },

  PitTask: {
    apiName: 'PitTask',
    displayName: 'PIT Task',
    pluralDisplayName: 'PIT Tasks',
    description: 'Work assigned to a PIT operator for one appointment.',
    domain: 'dockx',
    storage: 'RELATIONAL',
    apiPath: 'pit-tasks',
    backingModel: 'PitTask',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'bolShipmentNo',
    statusProperty: 'status',
    properties: {
      appointmentId: {
        apiName: 'appointmentId',
        displayName: 'Appointment',
        baseType: 'integer',
      },
      bolShipmentNo: {
        apiName: 'bolShipmentNo',
        displayName: 'BOL / Shipment #',
        baseType: 'string',
        description: 'Denormalized from the linked Appointment for board display.',
      },
      carrier: {
        apiName: 'carrier',
        displayName: 'Carrier',
        baseType: 'string',
        description: 'Denormalized from the linked Appointment for board display.',
      },
      doorName: {
        apiName: 'doorName',
        displayName: 'Door',
        baseType: 'string',
        nullable: true,
        description: 'Denormalized from the linked Appointment for board display.',
      },
      operatorName: {
        apiName: 'operatorName',
        displayName: 'Operator',
        baseType: 'string',
        nullable: true,
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'PitTaskStatus',
      },
      type: {
        apiName: 'type',
        displayName: 'Type',
        baseType: 'string',
        valueType: 'PitTaskType',
      },
      startedAt: {
        apiName: 'startedAt',
        displayName: 'Started At',
        baseType: 'timestamp',
        nullable: true,
      },
      completedAt: {
        apiName: 'completedAt',
        displayName: 'Completed At',
        baseType: 'timestamp',
        nullable: true,
      },
    },
  },

  // ─── Operations Hub domain ─────────────────────────────────────────
  Employee: {
    apiName: 'Employee',
    displayName: 'Employee',
    pluralDisplayName: 'Employees',
    description: 'A member of the site team.',
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'employees',
    backingModel: 'Employee',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'fullName',
    properties: {
      fullName: {
        apiName: 'fullName',
        displayName: 'Full Name',
        baseType: 'string',
      },
      firstName: {
        apiName: 'firstName',
        displayName: 'First Name',
        baseType: 'string',
      },
      lastName: {
        apiName: 'lastName',
        displayName: 'Last Name',
        baseType: 'string',
      },
      email: { apiName: 'email', displayName: 'Email', baseType: 'string' },
      shift: {
        apiName: 'shift',
        displayName: 'Shift',
        baseType: 'string',
        valueType: 'Shift',
      },
      jobRole: {
        apiName: 'jobRole',
        displayName: 'Job Role',
        baseType: 'string',
        valueType: 'JobRole',
      },
      hireDate: {
        apiName: 'hireDate',
        displayName: 'Hire Date',
        baseType: 'date',
      },
      active: { apiName: 'active', displayName: 'Active', baseType: 'boolean' },
      photoUrl: {
        apiName: 'photoUrl',
        displayName: 'Photo',
        baseType: 'string',
        nullable: true,
      },
      shirtSize: {
        apiName: 'shirtSize',
        displayName: 'Shirt Size',
        baseType: 'string',
        nullable: true,
      },
      birthday: {
        apiName: 'birthday',
        displayName: 'Birthday',
        baseType: 'date',
        nullable: true,
      },
      cwr: {
        apiName: 'cwr',
        displayName: 'CWR',
        baseType: 'boolean',
        description: 'Contingent worker rather than a GXO badge employee.',
      },
      phoneNumber: {
        apiName: 'phoneNumber',
        displayName: 'Phone',
        baseType: 'string',
        nullable: true,
      },
      cwid: {
        apiName: 'cwid',
        displayName: 'CWID',
        baseType: 'string',
        nullable: true,
      },
      notes: {
        apiName: 'notes',
        displayName: 'Notes',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Skill: {
    apiName: 'Skill',
    displayName: 'Skill',
    pluralDisplayName: 'Skills',
    description: 'A trainable competency employees are assessed against.',
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'skills',
    backingModel: 'Skill',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'name',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      jobRoles: {
        apiName: 'jobRoles',
        displayName: 'Job Roles',
        baseType: 'string[]',
        description:
          'Roles the skill applies to — normally JobRole values, but the list is open-ended. Persisted as a JSON string column.',
      },
      process: {
        apiName: 'process',
        displayName: 'Process',
        baseType: 'string',
        nullable: true,
      },
      action: {
        apiName: 'action',
        displayName: 'Action',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  EmployeeSkill: {
    apiName: 'EmployeeSkill',
    displayName: 'Skill Rating',
    pluralDisplayName: 'Skill Ratings',
    description: "An assessment of one employee's proficiency in one skill.",
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'ratings',
    backingModel: 'EmployeeSkillRating',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'skill',
    properties: {
      employeeId: {
        apiName: 'employeeId',
        displayName: 'Employee',
        baseType: 'integer',
      },
      skill: {
        apiName: 'skill',
        displayName: 'Skill',
        baseType: 'string',
        description: 'Skill name; matched by name rather than by id.',
      },
      rating: {
        apiName: 'rating',
        displayName: 'Rating',
        baseType: 'integer',
        valueType: 'SkillRating',
      },
      dateAssessed: {
        apiName: 'dateAssessed',
        displayName: 'Date Assessed',
        baseType: 'date',
      },
      assessedBy: {
        apiName: 'assessedBy',
        displayName: 'Assessed By',
        baseType: 'string',
      },
      notes: {
        apiName: 'notes',
        displayName: 'Notes',
        baseType: 'string',
        nullable: true,
      },
    },
  },

  Coaching: {
    apiName: 'Coaching',
    displayName: 'Coaching Opportunity',
    pluralDisplayName: 'Coaching Opportunities',
    description: 'A coaching conversation opened against an employee.',
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'coaching',
    backingModel: 'Coaching',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'title',
    statusProperty: 'status',
    properties: {
      employeeId: {
        apiName: 'employeeId',
        displayName: 'Employee',
        baseType: 'integer',
      },
      title: { apiName: 'title', displayName: 'Title', baseType: 'string' },
      notes: {
        apiName: 'notes',
        displayName: 'Notes',
        baseType: 'string',
        nullable: true,
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'CoachingStatus',
      },
      dateOpened: {
        apiName: 'dateOpened',
        displayName: 'Opened',
        baseType: 'timestamp',
      },
      dateClosed: {
        apiName: 'dateClosed',
        displayName: 'Closed',
        baseType: 'timestamp',
        nullable: true,
      },
    },
  },

  Contact: {
    apiName: 'Contact',
    displayName: 'Contact',
    pluralDisplayName: 'Contacts',
    description: 'An internal or external person the site needs to reach.',
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'contacts',
    backingModel: 'Contact',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'fullName',
    properties: {
      fullName: {
        apiName: 'fullName',
        displayName: 'Full Name',
        baseType: 'string',
      },
      company: { apiName: 'company', displayName: 'Company', baseType: 'string' },
      role: { apiName: 'role', displayName: 'Role', baseType: 'string' },
      phone: { apiName: 'phone', displayName: 'Phone', baseType: 'string' },
      email: { apiName: 'email', displayName: 'Email', baseType: 'string' },
      category: {
        apiName: 'category',
        displayName: 'Category',
        baseType: 'string',
      },
    },
  },

  Equipment: {
    apiName: 'Equipment',
    displayName: 'Equipment',
    pluralDisplayName: 'Equipment',
    description: 'A tracked asset: PIT, scanner, printer or other.',
    domain: 'opshub',
    storage: 'RELATIONAL',
    apiPath: 'equipments',
    backingModel: 'Equipment',
    primaryKey: 'id',
    primaryKeyType: 'integer',
    titleProperty: 'name',
    statusProperty: 'status',
    properties: {
      name: { apiName: 'name', displayName: 'Name', baseType: 'string' },
      type: {
        apiName: 'type',
        displayName: 'Type',
        baseType: 'string',
        valueType: 'EquipmentType',
      },
      status: {
        apiName: 'status',
        displayName: 'Status',
        baseType: 'string',
        valueType: 'EquipmentStatus',
      },
      assignedToId: {
        apiName: 'assignedToId',
        displayName: 'Assigned To',
        baseType: 'integer',
        nullable: true,
      },
      lastInspected: {
        apiName: 'lastInspected',
        displayName: 'Last Inspected',
        baseType: 'date',
        nullable: true,
      },
      serialNumber: {
        apiName: 'serialNumber',
        displayName: 'Serial Number',
        baseType: 'string',
      },
      notes: {
        apiName: 'notes',
        displayName: 'Notes',
        baseType: 'string',
        nullable: true,
      },
    },
  },
} as const satisfies Record<string, ObjectTypeDefinition>;

export type ObjectTypeApiName = keyof typeof OBJECT_TYPES;
